### ISSUE TITLE
大佬 关于这个插件能不能调整为打开target文件所在目录

### ISSUE THREAD

**Issue by canxi** [lcl100/idea-java-to-class-plugin#1]
不得不说这个插件非常好用，但是我的多模块项目可能会有几个项目合并在一起的情况，在打开outclass目录的时候会找不到class，想一个功能在编辑器页面中右键直接去find到target所在类的.class文件，而不是在导航树视图右键查找，并展示

**Comment by lcl100** [comment]
感谢你的使用和反馈，对于你的提议我已经考虑，近期应该就会发布新的版本，请静候。

**Comment by lcl100** [comment]
> 不得不说这个插件非常好用，但是我的多模块项目可能会有几个项目合并在一起的情况，在打开outclass目录的时候会找不到class，想一个功能在编辑器页面中右键直接去find到target所在类的.class文件，而不是在导航树视图右键查找，并展示

已经添加该功能，并已经在插件市场发布，可以试试看。

**Comment by canxi** [comment]
感谢大佬，功能使用正常
